// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './patrick-hand.ttf';
import glyphData from './glyphData.json';
import glyphDataById from './glyphDataById.json';

const bundle = {
  version: 0,
  family: 'Patrick Hand Tegaki',
  lineCap: 'round' as const,
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Patrick Hand Tegaki'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1042,
  descender: -312,
  glyphData,
  glyphDataById,
  features: ['frac', 'liga', 'locl'],
} as const;

export default bundle;
