// src/scene/CloudsConfig.ts
// Volumetric clouds configuration -- generated by IslandDebug.
// Paste this entire file to replace src/scene/CloudsConfig.ts

// -- Mesh placement (world-space centre + scale) ---
export const posX   = 0.0000;
export const posY   = 258.0000;
export const posZ   = -242.0000;
export const scaleX = 2000.0000;
export const scaleY = 109.0000;
export const scaleZ = 620.0000;

// -- Wind (right -> left) ---
export const windSpeed = 0.0150;

// -- Noise ---
export const noiseScale = 2.0000;

// -- Turbulence (domain warp) ---
export const turbulenceStrength = 0.1600;
export const turbulenceSpeed    = 0.0420;

// -- Shape ---
export const threshold = 0.9100;
export const range     = 0.3450;
export const opacity   = 0.5950;
export const edgeFade  = 0.5000;

// -- Quality ---
export const marchSteps = 64;

// -- Day colors ---
export const dayR = 1.0000;
export const dayG = 1.0000;
export const dayB = 1.0000;

// -- Night colors ---
export const nightR = 0.1200;
export const nightG = 0.1300;
export const nightB = 0.1100;