// src/scene/IslandConfig.ts
// Island placement configuration — generated by IslandDebug.
// Paste this entire file to replace src/scene/IslandConfig.ts

// ── Positions ─────────────────────────────────────────────────────────────────
export const islandPosition = { x: 0.0000, y: -0.8000, z: -3.3000 };
export const firecampOffset = { x: 0.0080, y: 1.0000, z: 0.4000 };
export const palmtreeOffset = { x: -0.4500, y: 1.0000, z: -0.3000 };
export const radioOffset    = { x: -0.7470, y: 1.0000, z: 0.0960 };
export const swordOffset    = { x: 0.1550, y: 1.3270, z: 0.1570 };
export const pugOffset      = { x: 0.6500, y: 1.0000, z: 1.0000 };
export const tentOffset     = { x: 0.4800, y: 0.9700, z: -0.3500 };
export const dogBedOffset   = { x: 0.4450, y: 0.9580, z: -0.3100 };

// ── Scales ────────────────────────────────────────────────────────────────────
export const islandScale   = 0.2500;
export const firecampScale = 1.4000;
export const palmtreeScale = 0.4330;
export const radioScale    = 0.2200;
export const swordScale    = 0.2500;
export const pugScale      = 0.4500;
export const tentScale     = 1.8000;
export const dogBedScale   = 0.3000;

// ── Rotations ─────────────────────────────────────────────────────────────────
export const palmtreeRotY = 0.0000;
export const radioRotY    = 0.4954;
export const swordRot     = { x: 2.6364, y: 0.0834, z: 0.1664 };
export const pugRotY      = -0.4536;
export const tentRotY     = -0.4000;
export const dogBedRotY   = -1.9556;

// ── Foliage clusters ──────────────────────────────────────────────────────────
export const CLUSTER_MAIN = { wx: -0.0120, wz: -2.4380, minR: 1.0520, maxR: 1.9830 };
export const CLUSTER_PALM = { wx: -0.0040, wz: -3.1590, minR: 0.1500, maxR: 0.5850 };

// ── Foliage counts ────────────────────────────────────────────────────────────
export const GRASS_COUNT      = 200;
export const GRASS_COUNT_PALM = 90;
export const CLOVER_COUNT     = 69;

// ── Spawn edge padding ────────────────────────────────────────────────────────
export const SURFACE_EDGE_PADDING = 0.1;