// src/scene/OceanConfig.ts
// Ocean visual configuration — generated by IslandDebug.
// Paste this entire file to replace src/scene/OceanConfig.ts

// ── Foam ─────────────────────────────────────────────────────────────────────
export const foamCenterOffset = { x: -0.0100, y: 0.0000 }; // XZ nudge on top of the auto-baked island center
export const foamRadius       = 0.9300; // >1 pushes ring outward, <1 pulls inward
export const foamWidth        = 0.1490; // width of the foam band
export const foamIntensity    = 0.3300; // overall foam brightness
export const foamAnimSpeed    = 0.4500; // speed of animated shimmer
export const foamEdgeNoiseAmt = 0.0000; // brightness shimmer near edge
export const foamWobbleAmt    = 0.0600; // world-unit wobble of the foam line
export const foamWobbleFreq   = 4.2000; // spatial frequency of the wobble
export const foamWobbleSpeed  = 0.9700; // how fast the wobble animates

// ── Ocean Waves (normal-map scroll) ──────────────────────────────────────────
export const normalMapScale    = 0.1500;
export const normalMapStrength = 0.0900;
export const waveVelocity1     = { x: 0.0650, y: 0.0000 };
export const waveVelocity2     = { x: 0.0000, y: 0.0650 };
export const edgeFadeDistance  = 0.5400;

// ── Ocean Surface ─────────────────────────────────────────────────────────────
export const surfaceColor   = { r: 0.0000, g: 0.3500, b: 0.7700 }; // RGB tint (1,1,1 = no tint)
export const surfaceOpacity = 0.6100;

// ── Reflection ────────────────────────────────────────────────────────────────
export const reflectionStrength     = 0.4300; // 0 = skybox only, 1 = RT only
export const reflectionFresnelPower = 0.4000; // lower = visible at more angles
export const reflectionFloor        = 0.2200; // minimum reflectivity at any angle
export const skyReflectionBrightness = 1.0000; // scales the analytical skybox reflection (0 = none, 1 = full)
export const skyReflFalloff         = 6.5000; // sharpens near→far gradient: 1 = linear, 2 = squared, 4 = very steep
export const reflectionRTSize       = 512 as 256 | 512; // render target resolution

// ── Underwater ────────────────────────────────────────────────────────────────
export const oceanAbsorption    = { r: 0.1290, g: 0.0440, b: 0.0350 }; // per-channel fog depth
export const underwaterFogDist  = 80.0;                                  // far distance — objects beyond this are fully fogged
export const distortionStrength = 0.0115;
export const distortionSpeed    = 0.6200;
export const distortionScale    = 8.5000;

// ── Click Ripple Effect ───────────────────────────────────────────────────────
export const rippleSpeed           = 0.7;    // World-units/sec the ring expands (max radius = speed × lifetime)
export const rippleLifetime        = 1.0;    // Seconds before the wave fully fades out
export const rippleWidth           = 0.12;   // Width of the wave band in world units
export const rippleNormalStrength  = 1.2;    // Normal-perturbation amplitude — keep in line with wave normals
export const rippleMaxClickDistance = 70.0;  // Max XZ distance (world units) from camera for the effect to trigger