// src/scene/config/CabanaConfig.ts
// Cabana (tent) interior zoom + interior shade — generated by Debug.
// Paste this entire file to replace src/scene/config/CabanaConfig.ts

// ── Cabana zoom ───────────────────────────────────────────────────────────────
export const cabanaCamX   = 0.2400;
export const cabanaCamY   = 0.7400;
export const cabanaCamZ   = -3.0700;
export const cabanaPhi    = 6.6800;
export const cabanaPitch  = -0.4700;
export const cabanaFov    = 51.5000;

// ── Interior shade (world-space volume) ───────────────────────────────────────
// Center is an OFFSET added to islandPosition (same convention as tentOffset).
export const cabanaShadeX       = 0.3600;
export const cabanaShadeY       = 0.3100;
export const cabanaShadeZ       = -1.0800;
export const cabanaShadeRadiusX = 0.4300;
export const cabanaShadeRadiusY = 1.7800;
export const cabanaShadeRadiusZ = 1.3600;
export const cabanaShadeEdge    = 0.0800;
export const cabanaShadeColor   = 0x141414;
export const cabanaShadeStrength = 1.0000;

// ── Fade speeds (damp lambda) ─────────────────────────────────────────────────
// Asymmetric fade: revealing the interior (zooming in) is slow so the shade
// gently dissolves as the camera approaches; re-darkening (zooming out) is fast
// so the interior is hidden again almost immediately. Higher = snappier.
export const cabanaShadeRevealSpeed = 2.0000;   // fade-out while zoomed in (lower = slower)
export const cabanaShadeCoverSpeed  = 10.0000;  // fade back in on zoom out (higher = faster)