// src/scene/config/IslandConfig.ts
// Island placement configuration — generated by IslandDebug.
// Paste this entire file to replace src/scene/IslandConfig.ts

// ── Positions ─────────────────────────────────────────────────────────────────
export const islandPosition = { x: 0.0000, y: -0.8000, z: -3.3000 };
export const firecampOffset = { x: 0.0080, y: 1.0000, z: 0.4000 };
export const palmtreeOffset = { x: -0.4500, y: 1.0000, z: -0.3000 };
export const radioOffset    = { x: -0.8470, y: 1.0000, z: 0.0960 };
export const swordOffset    = { x: 0.1550, y: 1.3270, z: 0.1570 };
export const pugOffset      = { x: 0.6500, y: 1.0000, z: 1.0000 };
export const tentOffset     = { x: 0.4800, y: 0.9800, z: -0.3500 };
export const dogBedOffset      = { x: 0.0000, y: 0.8000, z: 3.3000 };
export const littleRocksOffset = { x: 0.3200, y: 0.9850, z: 0.7000 };
export const phoneOffset       = { x: 0.3300, y: 1.0540, z: 0.7720 };

// ── Scales ────────────────────────────────────────────────────────────────────
export const islandScale      = 0.2500;
export const firecampScale    = 1.4000;
export const palmtreeScale    = 0.4330;
export const radioScale       = 0.2200;
export const swordScale       = 0.2500;
export const pugScale         = 0.4500;
export const tentScale        = 0.0750;
export const dogBedScale      = 1.0000;
export const littleRocksScale = 0.7440;
export const phoneScale       = 0.1500;

// ── Rotations ─────────────────────────────────────────────────────────────────
export const palmtreeRotY   = 0.0000;
export const radioRotY      = 0.4954;
export const swordRot       = { x: 2.6364, y: 0.0834, z: 0.1664 };
export const pugRotY        = -0.4536;
export const tentRotY       = -0.4000;
export const dogBedRotY     = 0.0000;
export const littleRocksRot = { x: 0.0000, y: -3.1416, z: 0.0000 };
export const phoneRot       = { x: -0.3166, y: -0.0306, z: -0.0096 };

// ── Foliage clusters ──────────────────────────────────────────────────────────
export const CLUSTER_MAIN = { wx: -0.0120, wz: -2.8140, minR: 1.2750, maxR: 2.0000 };
export const CLUSTER_PALM = { wx: 0.1390, wz: -3.8180, minR: 0.3080, maxR: 0.8410 };

// ── Foliage counts ────────────────────────────────────────────────────────────
export const GRASS_COUNT      = 75;
export const GRASS_COUNT_PALM = 90;
export const CLOVER_COUNT     = 69;

// ── Spawn edge padding ────────────────────────────────────────────────────────
export const SURFACE_EDGE_PADDING = 0.1;

// ── Exclusion zone radii (grass spawn clearance around each surface object) ───
export const EXCL_R_BONFIRE = 0.42;
export const EXCL_R_TENT    = 0.60;   // custom tent — increase to push grass further out
export const EXCL_R_PALM    = 0.14;
export const EXCL_R_PUG     = 0.34;
export const EXCL_R_RADIO   = 0.26;
export const EXCL_R_ROCKS   = 0.20;