// src/scene/OceanConfig.ts
// Ocean visual configuration — generated by Debug.
// Paste this entire file to replace src/scene/OceanConfig.ts

// ── Foam ─────────────────────────────────────────────────────────────────────
export const foamCenterOffset = { x: -0.0100, y: -0.0700 }; // XZ nudge on top of the auto-baked island center
export const foamRadius       = 0.9400; // >1 pushes ring outward, <1 pulls inward
export const foamWidth        = 0.1610; // width of the foam band
export const foamIntensity    = 0.0800; // overall foam brightness
export const foamAnimSpeed    = 0.4500; // speed of animated shimmer
export const foamEdgeNoiseAmt = 0.1200; // brightness shimmer near edge
export const foamWobbleAmt    = 0.1500; // world-unit wobble of the foam line
export const foamWobbleFreq   = 4.1000; // spatial frequency of the wobble
export const foamWobbleSpeed  = 0.2700; // how fast the wobble animates
export const foamLineFrequency = 13.0000;
export const foamLineThickness = 0.0270;
export const foamLineCount     = 1.0000;
export const foamLineBreakup   = 0.0000;
export const foamLineColor     = { r: 1.0000, g: 0.9200, b: 1.0000 };

// ── Ocean Waves (normal-map scroll) ──────────────────────────────────────────
export const normalMapScale    = 0.1160;
export const normalMapStrength = 0.1400;
export const waveVelocity1     = { x: 0.0330, y: -0.0100 };
export const waveVelocity2     = { x: -0.0270, y: -0.0180 };
export const edgeFadeDistance  = 0.5400;

// Horizon haze, driven by the view's GRAZING ANGLE (not distance). The ocean
// plane edge and any grazing-angle reflection speck always sit where the line of
// sight is near-horizontal, so veil that band by blending the surface to the
// sky's horizon color there. Distance-based fog could never catch it because the
// horizon's distance changes with camera height; the grazing angle does not.
// Values are -viewDir.y (0 = looking dead horizontal at the horizon, ~1 = down).
// Full haze at the horizon, fading to none once the view tips below ~End.
export const horizonFadeStart  = 0.0000;  // -viewDir.y where the haze starts fading out
export const horizonFadeEnd    = 0.1800;  // -viewDir.y where the haze is fully gone (looking down)

// ── Surface Vertex Displacement (near-camera swell) ──────────────────────────
// Real geometry waves applied ONLY to the strip of ocean in front of the camera
// — amplitude fades to 0 with distance so it fuses seamlessly with the flat
// surface. Gives the waterline a wavy silhouette when entering/exiting the water.
export const surfaceWaveAmplitude   = 0.0500; // max vertical displacement (world units) near the camera
export const surfaceWaveLength      = 3.7000; // wavelength in world units (keep ≥ ~4× vertex spacing)
export const surfaceWaveSpeed       = 0.6000; // animation speed of the swell
export const surfaceWaveRange       = 18.0000; // XZ distance from camera over which the waves fade to flat
export const surfaceWaveForwardBias = 0.6000; // 0 = full radial ring around camera, 1 = only directly ahead
export const surfaceWaveSteepness   = 0.3900; // blend of the cross wave layer — adds choppiness
// The swell is camera-relative (follows the camera, biased ahead of its
// heading) and only meant for the moment the camera crosses the waterline. When
// the camera sits above the surface and looks toward the horizon (e.g. the pug
// zoom at y~0.43), the region's far edge lands right on the horizon line and its
// wave normal flashes a bright sky reflection that tracks the camera. Fade the
// whole effect out by camera height above the waterline so it only shows at the
// crossing, never as a horizon speck.
export const surfaceWaveHeightFadeStart = 0.1500; // camera |Y| where the swell starts fading out
export const surfaceWaveHeightFadeEnd   = 0.3000; // camera |Y| where the swell is fully gone

// ── Ocean Surface ─────────────────────────────────────────────────────────────
export const surfaceColor   = { r: 0.0000, g: 1.1800, b: 1.1700 }; // RGB tint (1,1,1 = no tint)
export const surfaceOpacity = 0.6100;
export const waterBlurStrength = 0.0240;
export const waterBlurRadius   = 3.0000;
export const waterBlurOpacity  = 0.3500;
export const waterlineCompositeOpacity = 0.1800;

// ── Waterline (Y is used by apple buoyancy physics) ──────────────────────────
export const waterlineY         = 0.0050;

// ── Edge-foam (ocean-side depth intersection foam) ──────────────────────────
// Industry-standard "intersection foam": the ocean shader reads the opaque
// scene depth and brightens fragments where the ocean grazes geometry behind
// it. Fully independent from the SDF foam ring around the island silhouette.
export const edgeFoamWidth     = 0.1400;  // world-space distance over which foam fades to nothing
export const edgeFoamIntensity = 0.4200;  // overall brightness of the depth-intersection foam
export const edgeFoamUnderwaterMul = 0.3500;  // dimming factor for the same effect with camera below water (silvery refraction sheen)
export const edgeFoamColor     = { r: 1.0000, g: 0.9700, b: 1.0000 };

// World-Z fade for edge foam. iOS 16-bit depth buffer causes flicker on back
// rocks (z ≈ -4.7..-5.6). Fade starts at the pug's world Z (-2.3) where
// precision is still clean, fully gone 1 unit behind. Desktop is off-scene.
// Pug world Z = islandPosition.z (-3.3) + pugOffset.z (+1.0) = -2.3
export const edgeFoamFadeStartZDesktop = -40.0000;
export const edgeFoamFadeEndZDesktop   = -60.0000;
export const edgeFoamFadeStartZMobile  = -1.5000;
export const edgeFoamFadeEndZMobile    = -3.0000; // was -3.5 — narrower ramp shrinks the world-space band where residual depth-capture jitter can partially show through the fade

// ── Reflection ────────────────────────────────────────────────────────────────
export const reflectionFresnelPower = 0.6500; // lower = visible at more angles
export const reflectionFloor        = 0.2200; // minimum reflectivity at any angle
export const skyReflectionBrightness = 1.0000; // scales the analytical skybox reflection (0 = none, 1 = full)
export const skyReflFalloff         = 6.5000; // sharpens near→far gradient: 1 = linear, 2 = squared, 4 = very steep

// ── Underwater ────────────────────────────────────────────────────────────────
export const oceanAbsorption    = { r: 0.1290, g: 0.0440, b: 0.0350 }; // per-channel fog depth
export const underwaterFogDist  = 80.0000;                                  // far distance — objects beyond this are fully fogged
export const distortionStrength = 0.0115;
export const distortionSpeed    = 0.6200;
export const distortionScale    = 8.5000;
export const distortionEdgeFade = 0.0600;

// ── Fish / Jellyfish Lighting ───────────────────────────────────────────────
// Drives the per-jellyfish PointLight (candela-ish intensity + reach in world
// units). Material recompiles are avoided by keeping light *count* constant —
// only the values below change at runtime.
export const jellyfishLightConfig = {
    intensity: 3.0000,
    distance: 1.5000,
};

// ── Click Ripple Effect ───────────────────────────────────────────────────────
export const rippleSpeed           = 0.7;    // World-units/sec the ring expands (max radius = speed × lifetime)
export const rippleLifetime        = 1;    // Seconds before the wave fully fades out
export const rippleWidth           = 0.12;   // Width of the wave band in world units
export const rippleNormalStrength  = 1.2;    // Normal-perturbation amplitude — keep in line with wave normals
export const rippleMaxClickDistance = 70;  // Max XZ distance (world units) from camera for the effect to trigger