// src/scene/OceanConfig.ts
// Ocean visual configuration — generated by Debug.
// Paste this entire file to replace src/scene/OceanConfig.ts

// ── Foam ─────────────────────────────────────────────────────────────────────
export const foamCenterOffset = { x: -0.0100, y: -0.0700 }; // XZ nudge on top of the auto-baked island center
export const foamRadius       = 0.9400; // >1 pushes ring outward, <1 pulls inward
export const foamWidth        = 0.1610; // width of the foam band
export const foamIntensity    = 0.4100; // overall foam brightness
export const foamAnimSpeed    = 0.4500; // speed of animated shimmer
export const foamEdgeNoiseAmt = 0.1200; // brightness shimmer near edge
export const foamWobbleAmt    = 0.1500; // world-unit wobble of the foam line
export const foamWobbleFreq   = 4.1000; // spatial frequency of the wobble
export const foamWobbleSpeed  = 0.2700; // how fast the wobble animates
export const foamLineFrequency = 13.0000;
export const foamLineThickness = 0.0270;
export const foamLineCount     = 1.0000;
export const foamLineBreakup   = 0.0000;
export const foamLineColor     = { r: 1.0000, g: 0.9200, b: 1.0000 };

// ── Ocean Waves (normal-map scroll) ──────────────────────────────────────────
export const normalMapScale    = 0.1160;
export const normalMapStrength = 0.1400;
export const waveVelocity1     = { x: 0.0330, y: -0.0100 };
export const waveVelocity2     = { x: -0.0270, y: -0.0180 };
export const edgeFadeDistance  = 0.5400;

// ── Ocean Surface ─────────────────────────────────────────────────────────────
export const surfaceColor   = { r: 0.0000, g: 1.1800, b: 1.1700 }; // RGB tint (1,1,1 = no tint)
export const surfaceOpacity = 0.6100;
export const waterBlurStrength = 0.0240;
export const waterBlurRadius   = 3.0000;
export const waterBlurOpacity  = 0.3500;
export const waterlineCompositeOpacity = 0.1800;

// ── Waterline on objects ─────────────────────────────────────────────────────
export const waterlineY         = 0.0050;
export const waterlineThickness = 0.0000;
export const waterlineSoftness  = 0.0170;
export const waterlineColor     = { r: 1.0000, g: 0.9300, b: 1.0000 };
export const waterlineIntensity = 0.3400;

// ── Reflection ────────────────────────────────────────────────────────────────
export const reflectionFresnelPower = 0.6500; // lower = visible at more angles
export const reflectionFloor        = 0.2200; // minimum reflectivity at any angle
export const skyReflectionBrightness = 1.0000; // scales the analytical skybox reflection (0 = none, 1 = full)
export const skyReflFalloff         = 6.5000; // sharpens near→far gradient: 1 = linear, 2 = squared, 4 = very steep

// ── Underwater ────────────────────────────────────────────────────────────────
export const oceanAbsorption    = { r: 0.1290, g: 0.0440, b: 0.0350 }; // per-channel fog depth
export const underwaterFogDist  = 80.0000;                                  // far distance — objects beyond this are fully fogged
export const distortionStrength = 0.0115;
export const distortionSpeed    = 0.6200;
export const distortionScale    = 8.5000;
export const distortionEdgeFade = 0.0600;

// ── Fish / Jellyfish Lighting ───────────────────────────────────────────────
export const jellyfishLightConfig = {
    intensity: 0.3300,
    distance: 0.7500,
};

export const fishNightLightingConfig = {
    nonJellyLightInfluence: 0.0300,
    jellyLightInfluence: 1.3500,
};

// ── Click Ripple Effect ───────────────────────────────────────────────────────
export const rippleSpeed           = 0.7;    // World-units/sec the ring expands (max radius = speed × lifetime)
export const rippleLifetime        = 1;    // Seconds before the wave fully fades out
export const rippleWidth           = 0.12;   // Width of the wave band in world units
export const rippleNormalStrength  = 1.2;    // Normal-perturbation amplitude — keep in line with wave normals
export const rippleMaxClickDistance = 70;  // Max XZ distance (world units) from camera for the effect to trigger